while :
do
    pixlet render scoreboard_lucky.star
    pixlet push --api-token eyJhbGciOiJFUzI1NiIsImtpZCI6IjY1YzFhMmUzNzJjZjljMTQ1MTQyNzk5ODZhMzYyNmQ1Y2QzNTI0N2IiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL2FwaS50aWRieXQuY29tIiwiZXhwIjoxNjcxNDg0NTM3LCJpYXQiOjE2Mzk5NDg1MzcsImlzcyI6Imh0dHBzOi8vYXBpLnRpZGJ5dC5jb20iLCJzdWIiOiIxcHJwbHh0SW9RV2l3TXVvcXlmOTVuSEo0OVEyIiwic2NvcGUiOiJkZXZpY2UiLCJkZXZpY2UiOiJ1bmZhaWxpbmdseS1wcmVtaXVtLXNldHRsaW5nLWFuZ2VsZmlzaC0wNzAifQ.V_19nlNkgDGMT1ozbkwAYKjYiRIBy10V0YasvndguAlaLFpU143AyDRT53g79xvfrGc5dFiCmKBu_mSzxvKbTA unfailingly-premium-settling-angelfish-070 scoreboard_lucky.webp LuckiestScore
    sleep 10
done